# Generated by Django 4.1.1 on 2022-10-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='social_networks/image/', verbose_name='Логотип социальной сети')),
                ('name', models.CharField(max_length=50, verbose_name='Название социальной сети')),
                ('link', models.URLField(max_length=255, verbose_name='Ссылка на социальную сеть')),
            ],
            options={
                'verbose_name': 'Социальная сети',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
    ]
