version: "3.8"

services:
  photoshop_db:
    container_name: photoshop_db
    image: postgres:14-alpine
    ports:
      - '5436:5432'
    environment:
      - POSTGRES_DB=db_photoshop
      - POSTGRES_USER=ALebed
      - POSTGRES_PASSWORD=ALebed
    volumes:
      - photoshop_pgdata:/var/lib/postgresql/data
  django_ded:
    build:
      context: .
    container_name: django_ded
    ports:
      - "8060:8000"
    volumes:
      - static_volume:/django_ded/static
      - media_volume:/django_ded/media
    depends_on:
      - redis
      - photoshop_db
  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_volume:/data/
  celery:
    build: .
    command: celery -A ded worker -l info
    volumes:
      - ./django_ded/:/usr/src/app/
#    environment:
#      - CELERY_BROKER=redis://redis:6379
#      - CELERY_BACKEND=redis://redis:6379
    depends_on:
      - redis
  celery-beat:
    build: .
    command: celery -A ded beat -l info
    volumes:
      - ./django_ded/:/usr/src/app/
#    environment:
#      - CELERY_BROKER=redis://redis:6379
#      - CELERY_BACKEND=redis://redis:6379
    depends_on:
      - redis
volumes:
  photoshop_pgdata:
  static_volume:
  media_volume:
  redis_volume: