# Generated by Django 4.1.1 on 2022-10-29 12:42

import adminsortable.fields
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('marker', models.CharField(blank=True, choices=[('ХИТ', 'ХИТ'), ('ТОП', 'ТОП'), ('NEW', 'NEW'), ('АКЦИЯ', 'АКЦИЯ')], max_length=200, null=True, verbose_name='Маркер')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Услуги',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='FotoSliderBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Base_slider/image/', verbose_name='Фотография для слайдера')),
                ('text', models.CharField(max_length=34, verbose_name='Заголовок')),
                ('color', colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Цвет заголовка')),
                ('text_2', models.CharField(blank=True, max_length=34, null=True, verbose_name='Заголовок_2')),
                ('color_2', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None, verbose_name='Цвет заголовка_2')),
            ],
            options={
                'verbose_name': 'Главный Фотослайдер',
                'verbose_name_plural': 'Главный Фотослайдер',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Раздел')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Левая панель',
                'verbose_name_plural': 'Левая панель',
            },
        ),
        migrations.CreateModel(
            name='MiniFotoSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='MiniSlider/image/', verbose_name='Фотография для слайдера')),
                ('text_1', models.CharField(max_length=34, verbose_name='Заголовок_1')),
                ('color_1', colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Цвет заголовка_1')),
                ('text_2', models.CharField(blank=True, max_length=34, null=True, verbose_name='Заголовок_2')),
                ('color_2', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None, verbose_name='Цвет заголовка_2')),
                ('text_3', models.CharField(blank=True, max_length=34, null=True, verbose_name='Заголовок_3')),
                ('color_3', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None, verbose_name='Цвет заголовка_3')),
            ],
            options={
                'verbose_name': 'Мини-фотослайдер',
                'verbose_name_plural': 'Мини-фотослайдер',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, unique=True, verbose_name='Номер очереди')),
            ],
            options={
                'verbose_name': 'Номер очереди',
                'verbose_name_plural': 'Номер очереди',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='TimeForMiniSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_pause', models.IntegerField(default=4, verbose_name='Таймер времени в секундах')),
            ],
            options={
                'verbose_name': 'Таймер времени паузы для мини-фотослайдера',
                'verbose_name_plural': 'Таймер времени паузы для мини-фотослайдеров',
            },
        ),
        migrations.CreateModel(
            name='TimeSlideBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_pause', models.IntegerField(verbose_name='Таймер времени в секундах')),
            ],
            options={
                'verbose_name': 'Таймер времени паузы для фотослайдера',
                'verbose_name_plural': 'Таймер времени паузы для фотослайдеров',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фотографии')),
                ('project_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('category', adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.catalogservice')),
            ],
            options={
                'verbose_name': 'Фотографии',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['project_order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImageRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('catalogsevice', adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.catalogservice', verbose_name='Услуги')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.gallery', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Соединение и сортировка',
                'verbose_name_plural': 'Соединение и сортировка',
                'ordering': ['image_order'],
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='position',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.position', verbose_name='Номер очереди'),
        ),
    ]
